// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
	"time"
)

type Admin struct {
	AdminID  int64  `json:"admin_id"`
	RoleID   int64  `json:"role_id"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type Article struct {
	ArticleID int64  `json:"article_id"`
	CatID     int64  `json:"cat_id"`
	Title     string `json:"title"`
	Img       string `json:"img"`
	Breif     string `json:"breif"`
}

type ArticleTag struct {
	ArticleTagID int64 `json:"article_tag_id"`
	ArticleID    int64 `json:"article_id"`
	TagID        int64 `json:"tag_id"`
}

type Cat struct {
	CatID     int64  `json:"cat_id"`
	LookupKey string `json:"lookup_key"`
	Name      string `json:"name"`
}

type City struct {
	CityID int64  `json:"city_id"`
	Name   string `json:"name"`
}

type Consultunt struct {
	ConsultuntID int64  `json:"consultunt_id"`
	Name         string `json:"name"`
	Img          string `json:"img"`
	Title        string `json:"title"`
}

type Lookup struct {
	LookupKey string `json:"lookup_key"`
	Group     string `json:"group"`
	Value     string `json:"value"`
}

type Menu struct {
	MenuID int64  `json:"menu_id"`
	Title  string `json:"title"`
}

type MenuPage struct {
	MenuPageID int64 `json:"menu_page_id"`
	MenuID     int64 `json:"menu_id"`
	PageID     int64 `json:"page_id"`
}

type Page struct {
	PageID   int64          `json:"page_id"`
	Title    sql.NullString `json:"title"`
	Breif    sql.NullString `json:"breif"`
	Link     string         `json:"link"`
	MenuName string         `json:"menu_name"`
}

type Permission struct {
	PermissionID int64  `json:"permission_id"`
	Title        string `json:"title"`
}

type Program struct {
	ProgramID    int64          `json:"program_id"`
	CatID        int64          `json:"cat_id"`
	ConsultuntID int64          `json:"consultunt_id"`
	Title        string         `json:"title"`
	Img          string         `json:"img"`
	Breif        string         `json:"breif"`
	Content      string         `json:"content"`
	Goals        string         `json:"goals"`
	Location     string         `json:"location"`
	LocationNote sql.NullString `json:"location_note"`
	WhtaToLearn  string         `json:"whta_to_learn"`
	Hours        int32          `json:"hours"`
	Date         time.Time      `json:"date"`
}

type ProgramPlan struct {
	ProgramPlanID int64  `json:"program_plan_id"`
	ProgramID     int64  `json:"program_id"`
	Text          string `json:"text"`
	Breif         string `json:"breif"`
}

type Project struct {
	ProjectID int64        `json:"project_id"`
	CatID     int64        `json:"cat_id"`
	Title     string       `json:"title"`
	Img       string       `json:"img"`
	Date      sql.NullTime `json:"date"`
}

type Role struct {
	RoleID int64  `json:"role_id"`
	Title  string `json:"title"`
}

type RolePermission struct {
	RolePermissionID int64 `json:"role_permission_id"`
	RoleID           int64 `json:"role_id"`
	PermissionID     int64 `json:"permission_id"`
}

type Service struct {
	ServiceID int64  `json:"service_id"`
	CatID     int64  `json:"cat_id"`
	Title     string `json:"title"`
	Img       string `json:"img"`
	Breif     string `json:"breif"`
}

type StaticContent struct {
	StaticContentID int64          `json:"static_content_id"`
	Title           string         `json:"title"`
	Content         sql.NullString `json:"content"`
	Img             sql.NullString `json:"img"`
	Url             sql.NullString `json:"url"`
	Icon            sql.NullString `json:"icon"`
	LookupKey       string         `json:"lookup_key"`
}

type Tag struct {
	TagID int64  `json:"tag_id"`
	Title string `json:"title"`
}

type Testemonial struct {
	TestemonialID int64  `json:"testemonial_id"`
	Name          string `json:"name"`
	Img           string `json:"img"`
	Content       string `json:"content"`
}

type User struct {
	UserID     int64          `json:"user_id"`
	Name       string         `json:"name"`
	Emial      string         `json:"emial"`
	Phone      string         `json:"phone"`
	Job        sql.NullString `json:"job"`
	Company    sql.NullString `json:"company"`
	DeviceUuid sql.NullString `json:"device_uuid"`
}
